version: '3.1'

services:
  postgres:
    build: .
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_DB: students
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./01_seeding.sql:/docker-entrypoint-initdb.d/01_seeding.sql
      - ./02_role-creator.sql:/docker-entrypoint-initdb.d/02_role-creator.sql
      - ./03_students.sql:/docker-entrypoint-initdb.d/03_students.sql
      - ./04_data.sql:/docker-entrypoint-initdb.d/04_data.sql

volumes:
  postgres_data: