version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./rdata:/data
      
  redis-insight:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"

volumes:
  rdata:
     